"""Alert notification system: dry-run (file) or SMTP (MailHog).

Author: Armand Amoussou
"""

from __future__ import annotations

import datetime
import json
import smtplib
from email.mime.text import MIMEText
from pathlib import Path

from app.observability.logger import get_logger
from app.schemas.financial_output import AlertPayload

logger = get_logger("notifier")


def send_alert(
    alert: AlertPayload,
    mode: str = "dry_run",
    output_dir: str = "./out/alerts",
    smtp_host: str = "localhost",
    smtp_port: int = 1025,
) -> bool:
    """Send an alert via the configured mode.

    Returns True if sent successfully.
    """
    if mode == "dry_run":
        return _write_dry_run(alert, output_dir)
    elif mode == "smtp":
        return _send_smtp(alert, smtp_host, smtp_port)
    else:
        logger.error("unknown_alert_mode", mode=mode)
        return False


def _write_dry_run(alert: AlertPayload, output_dir: str) -> bool:
    """Write alert to local file system."""
    try:
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        ts = datetime.datetime.now(tz=datetime.timezone.utc).strftime("%Y%m%d_%H%M%S")
        filename = f"alert_{alert.supplier_id}_{ts}.json"
        file_path = out_path / filename
        file_path.write_text(
            alert.model_dump_json(indent=2),
            encoding="utf-8",
        )
        logger.info(
            "alert_dry_run",
            supplier_id=alert.supplier_id,
            file=str(file_path),
        )
        return True
    except Exception as e:
        logger.error("alert_dry_run_error", error=str(e))
        return False


def _send_smtp(
    alert: AlertPayload,
    smtp_host: str,
    smtp_port: int,
) -> bool:
    """Send alert via SMTP (MailHog in dev)."""
    try:
        subject = (
            f"[RISK ALERT] {alert.supplier_id} - "
            f"{alert.current_risk_level} (score: {alert.global_score})"
        )
        body = _format_email_body(alert)
        msg = MIMEText(body, "plain", "utf-8")
        msg["Subject"] = subject
        msg["From"] = "risk-system@supplier-risk.local"
        msg["To"] = "supply-team@supplier-risk.local"

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.sendmail(msg["From"], [msg["To"]], msg.as_string())

        logger.info(
            "alert_smtp_sent",
            supplier_id=alert.supplier_id,
            subject=subject,
        )
        return True
    except Exception as e:
        logger.error("alert_smtp_error", error=str(e))
        return False


def _format_email_body(alert: AlertPayload) -> str:
    """Format alert as readable plain-text email."""
    lines = [
        f"SUPPLIER RISK ALERT",
        f"====================",
        f"",
        f"Supplier: {alert.supplier_name} ({alert.supplier_id})",
        f"Date: {alert.as_of_date}",
        f"Trigger: {alert.trigger_reason}",
        f"",
        f"Risk Level: {alert.current_risk_level}",
        f"Global Score: {alert.global_score}/100",
    ]
    if alert.financial_score is not None:
        lines.append(f"Financial Score: {alert.financial_score}/100")
    if alert.previous_risk_level:
        lines.append(f"Previous Level: {alert.previous_risk_level}")
    lines.append("")
    if alert.risk_drivers:
        lines.append("Risk Drivers:")
        for d in alert.risk_drivers:
            lines.append(f"  - {d}")
        lines.append("")
    if alert.recommended_actions:
        lines.append("Recommended Actions:")
        for a in alert.recommended_actions:
            lines.append(f"  - {a}")
        lines.append("")
    if alert.top_evidences:
        lines.append("Top Evidence:")
        for e in alert.top_evidences[:3]:
            lines.append(f"  - [{e.source.value}] {e.excerpt[:120]}")
            lines.append(f"    URL: {e.url}")
        lines.append("")
    lines.append("---")
    lines.append("Generated by Supplier Risk Assessment System")
    return "\n".join(lines)
